#!/usr/bin/env bash

podman rm -f $(podman ps -aq) 2> /dev/null
podman image rm -f controle 2> /dev/null
podman build -t controle .
podman run -d -p8080:8042 --name controle-estoque controle
podman ps 
